---
name: Day 003 Hello Jobs Part 1 Test

on: workflow_dispatch

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dariocurr/pytest-summary@main
        with:
          paths: Day003_Hello_Jobs_Part_1/**.py
